# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]
        metasyn-version: ["metasyn"]
        include:
          - metasyn-version: "git+https://github.com/sodascience/metasyn.git@main"
            python-version: "3.11"
          # - metasyn-version: "metasyn==0.6.0"
            # python-version: "3.11"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ${{ matrix.metasyn-version }}
        python -m pip install pylint pytest pydocstyle mypy nbval
        python -m pip install .
    - name: Lint with pylint
      run: |
        pylint metasyncontrib/disclosure
    - name: Check docstrings with pydocstyle
      run: |
        pydocstyle metasyncontrib/disclosure --convention=numpy --add-select=D417 --add-ignore="D102,D105"
    - name: Check types with MyPy
      run: |
        mypy metasyncontrib/disclosure
    - name: Test with pytest
      run: |
        pytest tests
    - name: Check notebook output
      run: |
        pytest --nbval-lax examples
